// Yapay zeka ile üretilen kişisel öneriler henüz oluşturulmadıysa ya da ağ
// hatası olduysa kullanılan, genel ve bilimsel temelli iyi-olma-hali
// hatırlatmaları. Tıbbi tavsiye değildir — herkese uygun, basit ve
// kanıta dayalı küçük alışkanlık önerileridir. Not Yaz ekranındaki günlük
// karşılama satırı ve zamanlanmış bildirimler bu havuzdan seçim yapar.
export const WELLNESS_TIPS: string[] = [
  // Hidrasyon
  "Bir bardak su içmeyi unutma. 💧",
  "Sabah kalkınca içtiğin ilk bardak su metabolizmanı uyandırır. 💧",
  "Susuzluk hissetmeden önce su içmek, konsantrasyonunu korur. 💧",
  "Kahve yerine bir bardak su, enerjini daha dengeli tutabilir. 💧",
  "Hafif baş ağrısı bazen sadece susuzluktandır, bir yudum su dene. 💧",
  "Yanında bir su şişesi bulundurmak, gün boyu içmeyi kolaylaştırır. 🚰",
  "Öğle yemeğinden önce bir bardak su, sindirime yardımcı olabilir. 💧",
  "Ekran karşısında saatler geçince susuzluğu unutmak kolaydır. 💻",
  "Vücudun büyük kısmı sudan oluşur, ona küçük bir hatırlatma borçlusun. 💧",
  "Limon dilimli su, sıradan suya keyifli bir alternatif olabilir. 🍋",
  "Egzersizden önce ve sonra su içmek toparlanmayı destekler. 🏃",
  "Sıcak havalarda su ihtiyacın normalden fazla olabilir. ☀️",
  "Bir bitki çayı da su hedefine katkı sağlar, çeşitlilik iyidir. 🍵",
  "Yorgun hissettiğinde önce bir bardak su dene, sonra devam et. 💧",
  "Uyanır uyanmaz telefona değil, suya uzanmak güzel bir alışkanlık. 💧",
  "Gün içinde su içmeyi hatırlamak için telefonuna alarm kurabilirsin. ⏰",
  "Cilt nemliliği de bir parça yeterli su içmekle ilgilidir. ✨",
  "Kafeinli içecekler susuzluğu artırabilir, arasına su serpiştir. ☕",
  "Küçük yudumlarla, gün boyu yayarak içmek tek seferde içmekten iyidir. 💧",
  "Su, en ucuz ve en etkili enerji takviyendir. 💧",

  // Uyku
  "Bu gece biraz daha erken uyumayı dene, zihnin sana teşekkür eder. 🌙",
  "Uyumadan önce ekran parlaklığını azaltmak uykuya geçişi kolaylaştırır. 🌙",
  "Düzenli bir uyku saati, vücut saatini dengeler. 🕰️",
  "Yatmadan bir saat önce telefonu bırakmak zihnini sakinleştirebilir. 📵",
  "Kısa bir gerinme, uykuya dalmadan önce rahatlamana yardımcı olabilir. 🧘",
  "Yorgun bir gün sonunda kendine erken yatma izni ver. 🛏️",
  "Uyku, hafızanın ve öğrenmenin en sessiz yardımcısıdır. 🧠",
  "Odanı biraz daha karanlık yapmak uyku kalitesini artırabilir. 🌑",
  "Gündüz kısa bir şekerleme, akşam uykusunu bozmayacak kadar kısa olsun. 😴",
  "Yatak odanı serin tutmak, daha derin uyumana yardımcı olabilir. ❄️",
  "Uyumadan önce derin bir nefes almak, günü geride bırakmana yardım eder. 🌬️",
  "Kafeini öğleden sonra kesmek, gece uykunu koruyabilir. ☕",
  "Uyku eksikliği ruh halini de etkiler, bu gece kendine iyilik yap. 🌙",
  "Sabah güne erken başlamak, akşam daha erken yorulmana yardımcı olur. 🌅",
  "Yatmadan önce yarının küçük bir planını yapmak zihnini rahatlatabilir. 📝",
  "Uyumadan önce hafif bir müzik dinlemek gevşemene yardımcı olabilir. 🎵",
  "Düzensiz uyku saatleri, düzenli olanlardan daha yorucu hissettirebilir. ⏳",
  "Bugün erken yatmak, yarının sana verdiği en ucuz hediyedir. 🎁",

  // Hareket / Egzersiz
  "Kısa bir yürüyüş zihnini tazeleyebilir. 🚶",
  "On dakikalık bir yürüyüş bile ruh halini gözle görülür şekilde iyileştirebilir. 🚶",
  "Merdiven çıkmak, asansöre göre kalbine küçük bir hediyedir. 🏃",
  "Uzun süre oturduysan, birkaç dakika ayakta durmak iyi gelebilir. 🧍",
  "Basit gerinme hareketleri, kaslarındaki gerginliği azaltabilir. 🤸",
  "Hareket etmek, sadece bedeni değil zihni de canlandırır. 🏃",
  "Bugün asansör yerine merdiveni denemeye ne dersin? 🪜",
  "Kısa bir dans molası, ruh halini anında değiştirebilir. 💃",
  "Düzenli hareket, uzun vadede enerji seviyeni artırabilir. ⚡",
  "Yürürken derin nefes almak, iki faydayı bir arada sunar. 🌬️",
  "Omuzlarını birkaç kez geriye doğru çevirmek gerginliği azaltabilir. 🙆",
  "Bahçede ya da parkta kısa bir tur, günün en iyi anı olabilir. 🌳",
  "Egzersiz sonrası salınan endorfinler doğal bir keyif kaynağıdır. 😊",
  "Bugün biraz daha fazla adım atmayı hedefleyebilirsin. 👣",
  "Sabah birkaç esneme hareketi, güne daha dinç başlamanı sağlayabilir. 🌅",
  "Uzun toplantılardan sonra kısa bir esneme molası ver. 🧘",
  "Bisiklete binmek hem hareket hem de küçük bir özgürlük hissi verir. 🚲",
  "Ev işleri bile bir tür harekettir, kendine bu konuda kredi ver. 🏠",
  "Haftada birkaç kez hafif tempolu bir yürüyüş kalbin için iyi bir alışkanlıktır. ❤️",
  "Vücudun hareket etmek için tasarlandı, ona bugün küçük bir fırsat ver. 🏃",
  "Bel ve sırt esnetmeleri, masa başı günlerin küçük bir dengeleyicisidir. 🪑",
  "Yavaş ve bilinçli bir yürüyüş, hızlı bir koşu kadar değerli olabilir. 🚶",
  "Kısa bir esneme, uzun bir günün ortasında büyük fark yaratabilir. 🤸",

  // Nefes / Farkındalık / Meditasyon
  "Birkaç dakikana ayır, derin bir nefes al. 🌿",
  "Dört saniye nefes al, dört saniye tut, dört saniye ver, kutu nefesi dene. 🌬️",
  "Bir dakikalık sessizlik bile zihnini toparlamana yardımcı olabilir. 🧘",
  "Nefesine odaklanmak, şu ana dönmenin en basit yoludur. 🌬️",
  "Kısa bir farkındalık molası, günün geri kalanını daha sakin geçirmene yardımcı olabilir. 🧘",
  "Omuzlarını gevşet, çenendeki gerginliği bırak, küçük ama etkili bir an. 😌",
  "Bazen en iyi şey hiçbir şey yapmadan birkaç dakika oturmaktır. 🍃",
  "Zihnin dolu hissettiğinde, üç derin nefes almak sıfırlamana yardımcı olabilir. 🌬️",
  "Şu anki duyguna isim vermek, onu anlamanın ilk adımıdır. 💭",
  "Kısa bir meditasyon, günün ortasında küçük bir sığınak olabilir. 🧘",
  "Gözlerini kapat, beş saniyeliğine sadece nefesini dinle. 🌬️",
  "Farkındalık, geçmişi ya da geleceği değil şu anı fark etmektir. 🍃",
  "Bedenindeki gerginliği fark etmek, onu bırakmanın ilk adımıdır. 🧘",
  "Bir fincan çayını yavaşça, dikkatini vererek içmeyi dene. 🍵",
  "Sessizlikte birkaç dakika kalmak, gürültülü bir günün panzehiri olabilir. 🤫",
  "Nefesini yavaşlatmak, kalp atışını da yavaşlatabilir. 🌬️",
  "Bugün bir anlığına durup sadece etrafını dinlemeyi dene. 👂",
  "Zihnin dağıldığında, nazikçe nefesine geri dönebilirsin. 🌬️",
  "Kısa bir yürüyüş meditasyonu, hem hareket hem huzur verebilir. 🚶",
  "Kendine şu an iyiyim demek bile küçük bir çapa olabilir. ⚓",
  "Güne başlarken bir dakikalık sessizlik, tonunu belirleyebilir. 🌅",
  "Telefonunu bir kenara bırakıp sadece nefes almaya izin ver. 📵",
  "Zihinsel bir mola, fiziksel bir mola kadar gereklidir. 🧠",

  // Beslenme
  "Bugün bir porsiyon meyve ya da sebze eklemeye ne dersin? 🥗",
  "Yavaş yemek yemek, doygunluk hissini daha net fark etmeni sağlar. 🍽️",
  "Renkli bir tabak, genelde daha dengeli bir öğün demektir. 🥦",
  "Atıştırmalık yerine bir avuç kuruyemiş iyi bir alternatif olabilir. 🥜",
  "Kahvaltıyı atlamak yerine hafif bir şeyler yemeyi dene. 🍳",
  "Yemek yerken telefonu bırakmak, tadını daha çok fark etmeni sağlar. 🍽️",
  "Susuzluk bazen açlıkla karıştırılır, önce bir bardak su dene. 💧",
  "Taze bir meyve, işlenmiş bir atıştırmalıktan çoğu zaman daha iyi hissettirir. 🍎",
  "Öğün aralarını çok uzun tutmamak enerjini dengede tutabilir. ⏳",
  "Bugün bir sebze yemeğini denemeye ne dersin? 🥕",
  "Yemek hazırlarken müzik açmak, süreci daha keyifli yapabilir. 🎵",
  "Az ama sık yemek, bazı günler daha iyi hissettirebilir. 🍽️",
  "Şekerli içecekler yerine su ya da bitki çayı deneyebilirsin. 🍵",
  "Yediklerine dikkat etmek, kendine gösterdiğin bir özen biçimidir. 🥗",
  "Yavaşça çiğnemek sindirime ve doygunluk hissine yardımcı olabilir. 🍽️",

  // Ekran molası / Dijital denge
  "Ekrana uzun süre baktıysan, gözlerine kısa bir mola ver. 👀",
  "20-20-20 kuralı: her 20 dakikada, 20 saniye, 20 adım uzağa bak. 👀",
  "Telefonunu birkaç dakikalığına başka bir odaya bırakmayı dene. 📵",
  "Bildirimlerden bir süreliğine uzaklaşmak zihnine alan açabilir. 🔕",
  "Sosyal medyadan kısa bir mola, zihnine biraz sessizlik kazandırabilir. 📵",
  "Ekran karşısında geçirdiğin süreyi fark etmek ilk adımdır. 📱",
  "Gözlerini birkaç saniyeliğine kapatmak bile küçük bir dinlenmedir. 👁️",
  "Bugün bir saatliğine telefonu sessize almayı dene. 🔕",
  "Yatmadan bir süre önce ekranlardan uzaklaşmak zihnini sakinleştirebilir. 🌙",
  "Dijital bir mola, gerçek bir mola kadar dinlendirici olabilir. 📵",
  "Sabah ilk yarım saati ekransız geçirmeyi deneyebilirsin. 🌅",
  "Bildirim sesleri, farkında olmadan stres seviyeni yükseltebilir. 🔔",
  "Kısa bir ekransız an, günün ortasında küçük bir nefes gibidir. 🍃",
  "Gözlerini dinlendirmek için uzak bir noktaya bakmayı dene. 👀",
  "Telefonsuz geçirdiğin dakikalar da bir tür kendine bakımdır. 📵",

  // Güneş ışığı / Doğa
  "Birkaç dakika güneş ışığı almak ruh haline iyi gelebilir. ☀️",
  "Açık havada kısa bir tur, zihnini tazeleyebilir. 🌳",
  "Bir ağacın altında birkaç dakika oturmak bile fark yaratabilir. 🌳",
  "Sabah güneşine birkaç dakika maruz kalmak, gün ritmini destekler. 🌅",
  "Doğada geçirilen zaman, stresi azaltmada etkili olabilir. 🍃",
  "Pencereyi aç, biraz temiz hava içeri girsin. 🪟",
  "Bugün dışarıda kısa bir yürüyüş için zaman ayırabilir misin? 🌤️",
  "Bulutlara bakmak bile küçük bir zihinsel dinlenme olabilir. ☁️",
  "Yeşilliklerle çevrili bir yerde birkaç dakika geçirmek iyi gelebilir. 🌿",
  "Balkonda ya da bahçede birkaç derin nefes almayı dene. 🌬️",
  "Doğal ışık, iç mekan ışığından daha canlandırıcı olabilir. ☀️",
  "Kısa bir bahçe ya da park molası, günün ortasında ferahlatıcı olabilir. 🌳",

  // Duruş / Ergonomi
  "Otururken sırtını dik tutmak, uzun vadede belini rahatlatabilir. 🪑",
  "Ekranını göz hizasına getirmek boynundaki yükü azaltabilir. 💻",
  "Uzun süre aynı pozisyonda kalmışsan, kalkıp gerinmeye ne dersin? 🧍",
  "Bileklerini birkaç kez döndürmek, gerginliği azaltabilir. 🖐️",
  "Masandan kalkıp birkaç adım atmak, duruşunu sıfırlamana yardımcı olur. 🚶",
  "Telefona bakarken boynunu çok fazla eğmemeye çalış. 📱",
  "Sandalyende otururken ayaklarının yere tam bastığından emin ol. 🪑",
  "Omuzlarını kulaklarından uzaklaştır, küçük ama etkili bir hareket. 🙆",
  "Uzun bir çalışma seansından sonra sırtını nazikçe germeyi dene. 🧘",

  // Sosyal bağlantı
  "Bugün sevdiğin biriyle kısa bir mesajlaşmaya ne dersin? 💬",
  "Bir arkadaşını aramak, ikinizin de gününü güzelleştirebilir. 📞",
  "Sevdiğin birine seni düşünüyorum demek küçük ama değerlidir. 💛",
  "Yalnız hissettiğinde, güvendiğin biriyle konuşmak iyi gelebilir. 🤝",
  "Bir gülümseme, hem sana hem karşındakine iyi gelebilir. 😊",
  "Bugün birine teşekkür etmeyi unutma. 🙏",
  "Kısa bir sohbet bile bağlılık hissini güçlendirebilir. 💬",
  "Sevdiklerinle vakit geçirmek, en doğal iyi olma hali kaynaklarından biridir. ❤️",
  "Birine yardım etmek, kendini de iyi hissettirebilir. 🤝",
  "Uzun zamandır konuşmadığın birine merhaba demeye ne dersin? 👋",

  // Minnettarlık / Kendine şefkat / Duygusal iyi olma
  "Duygularını yazıya dökmek, onları anlamanın ilk adımıdır. 😊",
  "Bugün minnettar olduğun bir şeyi düşünmeye ne dersin? 🙏",
  "Kendine bugün biraz daha nazik davranmayı dene. 💛",
  "Küçük bir başarını fark etmek ve kutlamak da önemlidir. 🌟",
  "Zor bir gün geçirdiysen, kendine de anlayış göstermeyi unutma. 💛",
  "Herkesin zorlandığı günler olur, bugün öyleyse kendine yumuşak davran. 🌧️",
  "Bir cümle bile olsa, bugünü kaydetmeye değer. 📝",
  "Kendine elinden geleni yaptım demek de bir tür şefkattir. 💛",
  "Bugün kendine küçük bir mola verebilirsin. ☕",
  "Mükemmel olmak zorunda değilsin, yeterli olman yeterli. 🌿",
  "Bir şeyi başaramadıysan bile, denemiş olman değerlidir. 💪",
  "Kendi ilerlemeni başkalarıyla değil, dünkü haline göre ölç. 📈",
  "Bugün seni gülümseten küçük bir şeyi fark etmeye çalış. 😊",
  "Duygularının hepsi geçerlidir, onları bastırmak zorunda değilsin. 💭",
  "Kendine karşı sabırlı olmak, güçlü olmanın bir biçimidir. 🌱",
  "Bugün kendine bir iyilik yap, ne kadar küçük olursa olsun. 🎁",
  "Geçmişi değiştiremezsin ama bugüne nazikçe yaklaşabilirsin. 🌤️",
  "Bazı günler sadece ayakta kalmak bile bir başarıdır. 💪",
  "Kendine söylediğin sözlere dikkat et, bir arkadaşınla konuşur gibi konuş. 💛",
  "Bugün için tek bir hedefin olsun: kendine iyi davranmak. 🌿",
  "Minnettarlık, elindekini fark etmenin en basit yoludur. 🙏",
  "Bir başarısızlık, senin değerini azaltmaz. 🌟",
  "Kendine zaman ayırmak bencillik değil, gerekliliktir. ⏳",
  "Bugün yeterince iyiyim demeye izin ver kendine. 💛",
  "Zorlandığın anları not almak bile ilerlemenin bir parçasıdır. 📝",

  // Genel küçük iyi-olma alışkanlıkları
  "Bugün nasıl geçti? Birkaç cümleyle günlüğüne not düşmeye ne dersin? 📝",
  "Küçük bir mola ver ve bugünün hislerini günlüğüne yaz. 🌿",
  "Kendine birkaç dakika ayır, bugünü nasıl hissettiğini yazmak iyi gelir. 💭",
  "Bir cümle bile olsa, bugünü günlüğüne not düşmeye değer. 📝",
  "Odanı biraz toparlamak bile zihnini ferahlatabilir. 🧹",
  "Sevdiğin bir kokuyu (kahve, çiçek, kitap) fark etmeye ne dersin? 👃",
  "Bugün yeni bir şey öğrenmeye birkaç dakika ayırabilirsin. 📚",
  "Sevdiğin bir şarkıyı dinlemek, ruh halini hızla değiştirebilir. 🎵",
  "Küçük bir yaratıcı an (çizim, yazı, müzik) zihnine iyi gelebilir. 🎨",
  "Bugün kendine iyi gidiyorum demek için bir sebep bul. 🌟",
  "Evcil hayvanınla (varsa) birkaç dakika vakit geçirmek rahatlatıcıdır. 🐾",
  "Bir bitkiyi sulamak bile küçük bir bakım ve farkındalık anıdır. 🌱",
  "Sıcak bir duş, günün yorgunluğunu üzerinden atmana yardımcı olabilir. 🚿",
  "Bugün için küçük ve ulaşılabilir bir hedef belirle. 🎯",
  "Kahvaltı sırasında telefonsuz birkaç dakika geçirmeyi dene. ☕",
  "Bir kitabın birkaç sayfasını okumak zihnine iyi gelebilir. 📖",
  "Odanı havalandırmak, tazelenmiş hissetmene yardımcı olabilir. 🪟",
  "Bugün yaptığın bir şeyi, kimseye söylemeden kendi içinde takdir et. 🌟",
  "Küçük bir düzen (masanı toplamak gibi) zihinsel ferahlık getirebilir. 🗂️",
  "Bugün gülümsemene neden olan bir anı hatırlamaya çalış. 😊",
];
